---
kind: pipeline
name: node16

steps:
  - name: test node 16
    image: node:16
    commands:
      - npm i
      - npm run build
      - npm run lint

---
kind: pipeline
name: node17

steps:
  - name: test node 17
    image: node:17
    failure: ignore
    commands:
      - npm i
      - npm run build
      - npm run lint
