---
kind: pipeline
name: node15

steps:
  - name: test node 15
    image: node:15
    commands:
      - npm i
      - npm run build
      - npm run lint

---
kind: pipeline
name: node16

steps:
  - name: test node 16
    image: node:16
    failure: ignore
    commands:
      - npm i
      - npm run build
      - npm run lint
