---
kind: pipeline
name: node14

steps:
  - name: test node 14
    image: node:14
    commands:
      - npm i
      - npm run build
      - npm run lint

---
kind: pipeline
name: node15

steps:
  - name: test node 15
    image: node:15
    failure: ignore
    commands:
      - npm i
      - npm run build
      - npm run lint
