version: '3'

services:

  weareopensourceVue:
    container_name: weareopensourceVue
    image: weareopensource/vue:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - weareopensourceVue:/data
    networks:
      - frontend
    depends_on:
      - weareopensourceNode
    environment:
      - "WAOS_VUE_api_host=waosnode"

  weareopensourceNode:
    container_name: weareopensourceNode
    image: weareopensource/node:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - weareopensourceNode:/data
    networks:
      - frontend
      - backend
    depends_on:
      - mongo
    environment:
      - "WAOS_NODE_db_uri=mongodb://mongo:27017/WaosNodeDev"
      - "WAOS_NODE_host=0.0.0.0"

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data
    networks:
      - backend
      
networks:
    frontend:
      driver: bridge
    backend:
      driver: bridge

volumes:
  weareopensourceVue:
  weareopensourceNode:
  mongo: