import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vuetify from 'vite-plugin-vuetify';
import { fileURLToPath, URL } from 'node:url';
import viteCompression from 'vite-plugin-compression';

// Load config - will be generated by generateConfig.js script
let appConfig = { port: 8080 };
try {
  const configModule = await import('./src/config/index.js');
  appConfig = configModule.default;
} catch {
  console.warn('Could not load config, using defaults. Run npm run config first.');
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  return {
    plugins: [
      vue({
        template: {
          compilerOptions: {
            // Support for runtime template compilation
            isCustomElement: (tag) => tag.startsWith('ion-'),
          },
        },
      }),
      // https://github.com/vuetifyjs/vuetify-loader/tree/master/packages/vite-plugin
      vuetify({
        autoImport: true,
      }),
      // Brotli compression for production
      viteCompression({
        verbose: true,
        disable: false,
        threshold: 10240,
        algorithm: 'brotliCompress',
        ext: '.br',
        deleteOriginFile: false,
      }),
    ],

    define: {
      __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: 'false',
    },

    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
      extensions: ['.js', '.json', '.jsx', '.mjs', '.ts', '.tsx', '.vue'],
    },

    server: {
      port: appConfig.port || 8080,
      strictPort: false,
      // Uncomment to proxy API requests
      // proxy: {
      //   '/api': {
      //     target: 'http://localhost:3000',
      //     changeOrigin: true,
      //   },
      // },
    },

    preview: {
      port: appConfig.port || 8080,
    },

    build: {
      outDir: 'dist',
      assetsDir: 'assets',
      sourcemap: mode !== 'production',
      rollupOptions: {
        output: {
          manualChunks: {
            'vue-vendor': ['vue', 'vue-router', 'pinia'],
            'vuetify-vendor': ['vuetify'],
            'utils-vendor': ['axios', 'lodash', 'moment'],
          },
        },
      },
      // Increase chunk size warning limit
      chunkSizeWarningLimit: 1000,
    },

    optimizeDeps: {
      include: ['vue', 'vue-router', 'pinia', 'vuetify', 'axios', 'lodash', 'moment', 'marked', 'md5', 'aos'],
    },
  };
});
